import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";

export default function Home() {
  const [data, setData] = useState([]);
  const [loading, setLoading] = useState(true);

  const token =
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5kcmFpbiIsImhhc2hQYXNzd29yZCI6IiQyYiQxMCRRUUIudjJLZmVITjAwa2duNUFmREd1b2ljZG1MZWdUanp4UU5oa0hJenluLmV1VTVvWDYvRyIsImlhdCI6MTY3Mzk2NDM5OSwiZXhwIjoxNjc0NTY5MTk5fQ.tOahd3bU1ZAyCj4hn1l3SBp7TcHk7et76KWZvCf-Hyw";

  useEffect(() => {
    const getAllData = async () => {
      const req = await fetch("/api/students", {
        method: "GET",
        headers: {
          Authorization: `Bearer ${token}`,
        },
      });

      const res = await req.json();

      if (res.message !== "success") {
        return setData(res);
      }

      setData(res.data);
      setLoading(false);
    };

    getAllData();
  }, []);
  return (
    <>
      <Head>
        <title>Data Students</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="container mx-auto">
          <div className="py-5 px-2">
            <Link
              href="/add"
              className="bg-cyan-500 text-white w-52 text-center py-3 inline-block font-bold mb-3 rounded-md hover:bg-cyan-600"
            >
              Add Data
            </Link>
            <table className="w-full p-2 border">
              <thead>
                <tr className="bg-slate-800 text-white text-left">
                  <th className="w-1/4 px-3 py-2">No</th>
                  <th className="w-1/4 px-3 py-2">Name</th>
                  <th className="w-1/4 px-3 py-2">Email</th>
                  <th className="w-1/4 px-3 py-2">Action</th>
                </tr>
              </thead>
              <tbody>
                {data.message || loading ? (
                  <tr>
                    <td colSpan="4" className="py-5 text-center">
                      {data.message || "loading...."}
                    </td>
                  </tr>
                ) : (
                  data.map((student, index) => (
                    <tr
                      key={student._id}
                      className={`${
                        index === data.length - 1 ? "" : "border-b"
                      } ${index % 2 === 0 ? "bg-gray-300" : ""}`}
                    >
                      <td className="px-3 py-2 truncate">{index + 1}</td>
                      <td className="px-3 py-2 truncate">{student.name}</td>
                      <td className="px-3 py-2 truncate">{student.email}</td>
                      <td className="px-3 py-2 flex gap-2 text-sm text-white items-center">
                        <button className="px-3 py-1 bg-green-500 rounded-full hover:bg-green-600">
                          Edit
                        </button>
                        <button className="px-3 py-1 bg-red-500 rounded-full hover:bg-red-600">
                          Remove
                        </button>
                      </td>
                    </tr>
                  ))
                )}
              </tbody>
            </table>
          </div>
        </div>
      </main>
    </>
  );
}
